services:
  #бд для кеширования
  redis:
    image: redis
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - microservices
  #бд для кейклоака
  keycloak_postgres:
    image: postgres:15
    container_name: keycloak-postgres
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    ports:
      - "5433:5432"
    volumes:
      - postgres_keycloak_data:/var/lib/postgresql/data
    networks:
      - keycloak_net
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U keycloak" ]
      interval: 10s
      timeout: 5s
      retries: 20
  #для кейклоака и экспорта конфига
  keycloak:
    image: quay.io/keycloak/keycloak:26.2
    container_name: keycloak
    command: start-dev --import-realm --metrics-enabled=true
    ports:
      - "8080:8080"
    environment:
      JAVA_OPTS: -Dkeycloak.migration.usersExportStrategy=REALM_FILE
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-postgres:5432/keycloak
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KC_HOSTNAME: localhost
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_FEATURES: account  # ← КЛЮЧЕВОЕ ИЗМЕНЕНИЕ
    volumes:
      - ./architecture/keycloak/realm-config.json:/opt/keycloak/data/import/realm-config.json
    depends_on:
      keycloak_postgres:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL","curl -fsS http://localhost:9000/healthy/ready || exit 1" ]  # ← исправил опечатку: exit1 → exit 1
      interval: 10s
      timeout: 5s
      retries: 50
    networks:
      - keycloak_net

  #krakenD
  krakend:
    image: devopsfaith/krakend:2.1.2
    container_name: krakend
    ports:
      - "8081:8080"
    expose:
      - 8081
    volumes:
      - ./architecture/krakend:/etc/krakend
    networks:
      - keycloak_net
      - microservices

  #бд для категорий товаров
  goods_categories_db:
    image: postgres:15
    container_name: goods_categories_db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    volumes:
      - postgres_goods_categories_db_data:/var/lib/postgresql/data
    networks:
      - microservices
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 20

  #микросервис для категорий товаров
  goodscategory:
    build:
      context: ./goodscategory
      dockerfile: Dockerfile
    container_name: goodscategory
    ports:
      - "8005:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - DB_HOST=postgres
    depends_on:
      goods_categories_db:
        condition: service_healthy
    networks:
      - microservices

  #бд для корзины
  basket_db:
    image: postgres:15
    container_name: basket_db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5435:5432"
    volumes:
      - postgres_basket_db_data:/var/lib/postgresql/data
    networks:
      - microservices
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 20

  #микросервис корзины
  basket:
    build:
      context: ./basket
      dockerfile: Dockerfile
    container_name: basket
    ports:
      - "8006:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      basket_db:
        condition: service_healthy
    networks:
      - microservices

  #микросервис чтобы хранить файлы
  minio:
    image: minio/minio
    container_name: minio
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=admin1234
      - MINIO_DEFAULT_BUCKETS=fashionconstuct
    command: server /data --console-address ":9001"
    networks:
      microservices:
        aliases:
          - minio-storage
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000" # API
      - "9001:9001" # Console
    restart: always

  #микросервис для обмена файлами
  file_service:
    build:
      context: ./fileservice
      dockerfile: Dockerfile
    container_name: file_service
    ports:
      - "8007:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - microservices


  #бд для конструктора магазину
  shop_db:
    image: postgres:15
    container_name: shop_db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5436:5432"
    volumes:
      - postgres_shop_db_data:/var/lib/postgresql/data
    networks:
      - microservices
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 20

  #микросервис для конструктора магазина
  shop_service:
    build:
      context: ./shop
      dockerfile: Dockerfile
    container_name: shop_service
    ports:
      - "8008:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      shop_db:
        condition: service_healthy
    networks:
      - microservices

volumes:
  postgres_keycloak_data:
  postgres_goods_categories_db_data:
  redis_data:
  postgres_basket_db_data:
  minio_data:
  postgres_shop_db_data:

networks:
  #нетворк для кейклоака
  keycloak_net:
    driver: bridge
  #нетворк для микросервисов
  microservices:
    driver: bridge
  api_gateaway:
    driver: bridge

