services:
  redis:
    image: redis
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - microservices

  minio:
    image: minio/minio
    container_name: minio
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin1234
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      files:
        aliases:
          - minio-storage

  keycloak:
    image: quay.io/keycloak/keycloak:26.2
    container_name: keycloak
    command: start-dev --import-realm --metrics-enabled=true
    ports:
      - "8080:8080"
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://db:5432/keycloak_postgres
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: postgres
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_PROXY: edge
      KC_PROXY_HEADERS: xforwarded
      KC_HTTP_ENABLED: "true"
      KC_HTTPS_ENABLED: "false"
      KC_HOSTNAME_STRICT: "false"
    volumes:
      - ./architecture/keycloak/realm-config.json:/opt/keycloak/data/import/realm-config.json
    networks:
      - keycloak_net
    depends_on:
      db:
        condition: service_healthy
        
  krakend:
    image: devopsfaith/krakend:2.9
    container_name: krakend
    ports:
      - "8081:8081"
    volumes:
      - ./architecture/krakend:/etc/krakend
    networks:
      - keycloak_net
      - microservices
      - fashion-network
    environment:
      - FC_ENABLE=1
      - FC_PARTIALS=/etc/krakend
      - FC_TEMPLATES=/etc/krakend
    depends_on:
      - keycloak

  productservice:
    build: ./productservice
    container_name: productservice
    ports:
      - "8083:8083"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: productdb
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USERNAME: admin
      RABBITMQ_PASSWORD: admin
      SERVER_PORT: 8083
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_started
    networks:
      - microservices
      - fashion-network

  cartservice:
    build: ./cartservice
    container_name: cartservice
    ports:
      - "8084:8084"
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USERNAME: admin
      RABBITMQ_PASSWORD: admin
      SERVER_PORT: 8084
    depends_on:
      - redis
      - rabbitmq
    networks:
      - microservices

  newsservice:
    build: ./newsservice
    container_name: newsservice
    ports:
      - "8085:8085"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: newsdb
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      SERVER_PORT: 8085
    depends_on:
      db:
        condition: service_healthy
    networks:
      - microservices
      - fashion-network

  orderservice:
    build: ./orderservice
    container_name: orderservice
    ports:
      - "8087:8087"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: orderdb
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USERNAME: admin
      RABBITMQ_PASSWORD: admin
      SERVER_PORT: 8087
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_started
    networks:
      - microservices

  basket:
    build: ./basket
    container_name: basket
    ports:
      - "8086:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/basket_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      db:
        condition: service_healthy
    networks:
      - microservices

  fileservice:
    build: ./fileservice
    container_name: fileservice
    ports:
      - "8082:8082"
    environment:
      MINIO_ENDPOINT: minio-storage
      MINIO_PORT: 9000
      MINIO_ACCESS_KEY: admin
      MINIO_SECRET_KEY: admin1234
      MINIO_BUCKET_NAME: fashionconstruct
      MINIO_PUBLIC_URL: http://localhost:9000
      MINIO_SECURE: "false"
      SERVER_PORT: 8082
    depends_on:
      - minio
    networks:
      - microservices
      - files
      - fashion-network
    
    
  userservice:
    build: ./userservice
    container_name: userservice
    ports:
      - "8088:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/userservice_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      KEYCLOAK_SERVER_URL: http://keycloak:8080
      KEYCLOAK_ADMIN_USERNAME: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    depends_on:
      db:
        condition: service_healthy
      keycloak:
        condition: service_started
    networks:
      - microservices
      - keycloak_net
      - fashion-network

  shop:
    build: ./shop
    container_name: shop
    ports:
      - "8089:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/shop_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      db:
        condition: service_healthy
    networks:
      - microservices
      - fashion-network

  # Frontend (Admin Panel)
  frontend:
    build:
      context: ./fashion
      args:
        VITE_API_URL: http://localhost:8081
        VITE_FAKE_AUTH: "false"
    container_name: frontend
    ports:
      - "3000:80"
    depends_on:
      - krakend
    networks:
      - fashion-network

  #rabbitmq
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    command: >
      sh -c "rabbitmq-plugins enable rabbitmq_prometheus && rabbitmq-server"
    ports:
      - "15672:15672"
      - "5672:5672"
      - "15692:15692"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit disk_free_limit 214748648
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - microservices
      - observability

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./architecture/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - observability
    healthcheck:
      test: [ "CMD", "wget", "--spider", "http://localhost:9090/-/healthy" ]
      interval: 10s
      timeout: 5s
      retries: 5

  loki:
    image: grafana/loki:2.9.2
    container_name: loki
    ports:
      - "3100:3100"
    volumes:
      - ./architecture/loki/loki-config.yaml:/etc/loki/loki-config.yaml
    healthcheck:
      test: [ "CMD", "wget", "--spider", "-q", "http://localhost:3100/ready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - observability
    

  tempo:
    image: grafana/tempo:2.4.1
    container_name: tempo
    ports:
      - "3200:3200"
    volumes:
      - ./architecture/tempo/tempo.yaml:/etc/tempo/tempo.yaml
    command:
    - -config.file=/etc/tempo/tempo.yaml
    networks:
      - observability

  alloy:
    image: grafana/alloy:latest
    container_name: alloy
    user: root
    ports:
      - "9080:9080" # HTTP interface
      - "4317:4317" # OTLP gRPC
      - "4318:4318" # OTLP http
    volumes:
      - ./architecture/alloy/config.alloy:/etc/alloy/config.alloy:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/log:/var/log:ro
    environment:
      GRAFANA_LOKI_URL: http://loki:3100/loki/api/v1/push
    command:
      - run
      - --server.http.listen-addr=0.0.0.0:9080
      - --storage.path=/var/lib/alloy/data
      - /etc/alloy/config.alloy
    networks:
      - observability

  grafana:
    image: grafana/grafana:10.3.1
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      prometheus:
        condition: service_healthy
      loki:
        condition: service_healthy
      tempo:
        condition: service_started
      alloy:
        condition: service_started
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: true
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_METRICS_ENABLED: "true"
    volumes:
      - ./architecture/grafana/provisioning:/etc/grafana/provisioning
      - ./architecture/grafana/dashboards:/var/lib/grafana/dashboards
    healthcheck:
      test: [ "CMD", "wget", "--spider", "http://localhost:3000/api/health" ]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - observability

  db:
    image: postgres:15-alpine
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_MULTIPLE_DATABASES: basket_db,shop_db,keycloak_postgres,userservice_db,productdb,cartdb,newsdb,orderdb
    volumes:
      - ./init-multiple-databases.sh:/docker-entrypoint-initdb.d/init-multiple-databases.sh
      - postgres_data:/var/lib/postgresql_data
    ports:
      - "5432:5432"
    networks:
      - microservices
      - keycloak_net
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -p 5432" ]
      interval: 10s
      timeout: 5s
      retries: 20

#волум
volumes:
  postgres_keycloak_data:
  postgres_goods-categories_data:
  redis_data:
  postgres_basket_data:
  minio_data:
  loki_data:
  loki_chunks:
  loki_index:
  loki_rules:
  rabbitmq_data:
  tempo_data:
  postgres_data:
  
networks:
  #нетворк для кейклоака
  keycloak_net:
    driver: bridge
  #нетворк для микросервисов
  microservices:
    driver: bridge
  api_gateaway:
    driver: bridge
  #нетворск для обесрвабилити
  observability:
    driver: bridge
  files:
    driver: bridge
  # Fashion admin frontend network
  fashion-network:
    driver: bridge



