spring:
  application:
    name: order-service
  
  datasource:
    url: jdbc:postgresql://${DB_HOST:db}:${DB_PORT:5432}/${DB_NAME:orderdb}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: ${SHOW_SQL:false}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    open-in-view: false
  
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
  
  rabbitmq:
    host: ${RABBITMQ_HOST:rabbitmq}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
    listener:
      simple:
        acknowledge-mode: auto
        retry:
          enabled: true
          initial-interval: 3000
          max-attempts: 3
          multiplier: 2

rabbitmq:
  exchange:
    order: order-exchange
  queue:
    stock-decrease: stock.decrease
    order-completed: order.completed
  routing-key:
    stock-decrease: stock.decrease
    order-completed: order.completed

server:
  port: ${SERVER_PORT:8087}

yookassa:
  shop-id: ${YOOKASSA_SHOP_ID:1246914}
  secret-key: ${YOOKASSA_SECRET_KEY:test_LZEYYDY3inXYgAlSiROF3a7L4h4z0_cxZ2l4IuMMPxM}
  api-url: ${YOOKASSA_API_URL:https://api.yookassa.ru/v3/payments}

yandex:
  delivery:
    api-url: ${YANDEX_DELIVERY_API_URL:https://b2b.taxi.yandex.net/b2b/cargo/integration/v2}
    api-token: ${YANDEX_DELIVERY_API_TOKEN:y0__xCd-KvSCBix9Bwgp8OMiRapyG8u0V5lGR_NrN_ay2g-CTuTww}
    source-platform-station: ${YANDEX_DELIVERY_SOURCE_STATION:05e809bb-4521-42d9-a936-0fb0744c0fb3}
    default-weight: ${YANDEX_DELIVERY_DEFAULT_WEIGHT:10000}

logging:
  level:
    com.marketplace.orderservice: ${LOG_LEVEL:INFO}
    org.springframework.amqp: ${LOG_LEVEL:INFO}
